name: ACCELQ Github-A Connect
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to (e.g. production, staging)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        uses: accelq/accelq-ci-github-actions@v1.4 
        with:
        # Your ACCELQ Application URL in the exact following format: https://<hostname>:<port_num>
        appURL: https://app.accelq.io
        # Your ACCELQ User ID
        userName: sandeep.dwadasi@claritisoftware.com
        # API key available in Profile section of ACCELQ : Sandeep
        apiKey: 8qX9PtCvC3RsMkuPKLcJclNX7OaHy1fWejLHymldt9k
        # Tenant Code displayed in the Profile section of ACCELQ : parent Proj name
        tenantCode: claritisoftware
        # This ID should come from the CI job you saved in ACCELQ application : scheduled job
        jobId: 1544
        # Run Params(optional) should be JSON string form example: '{"username": "John Todd", "password": "bxW&=UVw"}'
        runParam: # optional
        # Proxy Host (optional)
        proxyHost: # optional
        # Proxy Port (optional)
        proxyPort: # optional
        # Percentage ACCELQ test case failure (Optional), beyond which this Step in the Pipeline will be marked as a failure. If this is zero, even a single failed test will cause the Step to fail. If you never want to fail the Pipeline Step due to failing Automation tests, input -1. Input a valid integer between 0 and 100 or, -1.
        stepFailureThreshold: # optional
        # Maximum time to wait for the job to be picked up by an ACCELQ Agent. Default is 15 mins.
        maxWaitTimeInMins: # optional
          
